reject concurrent pre-receive hooks
Sandboxing the hook environment let multiple apps be deployed concurrently,
but git rejects commits if the target ref has been changed since the push began.

That can lead to a bad state where git-deploy hooks have modified the environment
but the commit is rejected.
This locking won't 100% prevent the bad state, but it reduces the window by the duration of
the pre-receive hook (i.e. <1 second instead of seconds->minutes)

diff --git a/test/test-hooks/pre-receive b/test/test-hooks/pre-receive
--- a/test/test-hooks/pre-receive
+++ b/test/test-hooks/pre-receive
@@ -1,8 +1,9 @@
 #!/bin/bash
 
 # exit if we see 'badfile' in the list of files
+# drop a breadcrumb and sleep if we see 'slowfile' in the list of files
 while read oldrev newrev refname; do
-	if [[ $oldrev =~ 0+ ]]; then
+	if [[ $oldrev =~ ^0+$ ]]; then
 		FILES=$(git show --pretty="format:" --name-only $newrev)
 	else
 		FILES=$(git diff --name-only $oldrev..$newrev)
@@ -10,5 +11,11 @@ while read oldrev newrev refname; do
 
 	for file in $FILES; do
 		[ $file != 'badfile' ] || exit 1
+		if [ "$file" == 'slowfile' ]; then
+			touch breadcrumb
+			sleep 5
+			# pick up breadcrumb if it exists; fail if it was stolen (by a concurrent hook)
+			[ -f breadcrumb ] && rm -f breadcrumb || exit 1
+		fi
 	done
 done
